# INI files are pretty simple to understand. 
# The syntax of INI files is a sequence of:
# [SECTION_NAME]
# KEY1=VALUE1
# KEY2=VALUE2
# ...
# 
# The "[SECTION_NAME]" defines a section named "SECTION_NAME", and the 
# "KEY1=VALUE1" lines defines key/value pairs inside of that section. That's it. 
#
# However, I use SECTION_NAME to set the "idName" of the product, 
# and the "KEY=VALUE" pairs to "set" the default values for that product.
# See the "[apple]" section below for an example, but note that not 
# all the fields actually need to be specified. The only field that
# actually needs to be specified is gName, like so: 
# [id_name]
# gName=A general name
# 
# Although, note that if "tags" isn't specified, then it'll default 
# to being empty. All the other fields will be randomly generated.
# For reference, the commented part below shows all acceptable field names 
# and an example for what value is accepted for it.
# [apple]
# gName=Apple
# tags=fruit,perishable
# buyPrice=$1.50
# sellPrice=$2.00
# lowBound=10
# unitString=Kg
# unitAmount=0.75
# stockAmount=64
# soldAmount=16
# 
# Note, unitString can be really any string, even one with spaces in it. 
# As well, tags is comma separated, so taking the [apple_crisps] as an example: 
# tags=canned,nonperishable,fruit
# Assigns apple_crisps the tags
# - "canned"
# - "nonperishable"
# - "fruit"
# You may include spaces between each comma, so 
# tags=canned,  nonperishable,  fruit
# is equivalent to 
# tags=canned,nonperishable,fruit
#
# I have some more notes to make:
# 1. Running the file "data_gen.exe" in this directory should be all you need to 
#    generate "output.json". As well...
# 2. ... about the output file, "output.json". The path to this file should be 
#    passed into "ProductDB.loadFromInit". After that, everything should be 
#    initialized, as if you loaded "dbfile.json" 
#    The point of "output.json" is merely to initialize everything. It's not 
#    meant to be used for storage. "dbfile.json", however, MUST be capable of 
#    efficient storage and retrieval.
# 3. Don't run data_gen.exe outside of this directory. It looks for input.ini
#    in the directory it's run from, so it's best not to move it anywhere else.
# 4. I haven't done much error handling with the program, so any parsing errors 
#    may kill the whole program, or just cause nonsensical output. Worst case scenario, 
#    this'll just corrupt the output.json file. The only thing I actually do is 
#    check for missing fields. I'll get to error handling when I can. 
# 5. I have not added soldDate yet, I'll get to that once I can.
# 6. Any line starting with "#" is a comment, so if you want to remove a KEY=VALUE pair, 
#    just prepend it with "#". However, much to my shock, "#" is allowed literally anywhere 
#    else. 

[apple]
gName=Apple
tags=fruit,perishable
buyPrice=$1.50
sellPrice=$2.00
lowBound=10
unitString=Kg
unitAmount=0.6
stockAmount=64
soldAmount=16

[lettuce]
gName=Lettuce
tags=vegetable,perishable
unitString=Kg
unitAmount=0.8

[lays_chips]
gName=Ketchup Chips
tags=snack,nonperishable

[orange]
gName=Orange
tags=fruit,perishable

[apple_crisps]
gName=Apple Crisps
tags=fruit,snack,nonperishable

[can_tomato_sauce]
gName=Canned Tomato Sauce
tags=canned,nonperishable,fruit

[can_peach]
gName=Canned Peaches
tags=canned,nonperishable,fruit
unitString=L

[penne_noodle]
gName=Penne
tags=pasta,nonperishable

[ice_cream]
gName=Ice Cream
tags=snack,nonperishable,frozen
unitString=L
unitAmount=1.4


